apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-dmefrain-02
  labels:
    app: student-dmefrain-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-dmefrain-02
  template:
    metadata:
      labels:
        app: student-dmefrain-02
    spec:
      containers:
        - name: student-dmefrain-02
          image: us-central1-docker.pkg.dev/devsecops-lab-464018/student-dmefrain-02
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"