apiVersion: v1
kind: Service
metadata:
  name: student-dmefrain-02-service
spec:
  selector:
    app: student-dmefrain-02
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP